markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: false
permalink: none
url: http://designwithfontforge.com
title: Design With FontForge
subtitle: A book about how to create new typefaces using FontForge
